import type { AircraftGenome } from '../aircraft/genome'
import type { LearnerProfile } from '../shared/types'
import { round } from '../shared/math'
import { instructionVerb } from './copy'

export interface Point2D { x: number; y: number }
export interface FoldCrease { start: Point2D; end: Point2D; orientation: 'mountain' | 'valley'; movingSide: 'left' | 'right' | 'top' | 'bottom' | 'both'; targetAngleDeg: number }
export interface FoldStep { id: string; number: number; title: string; instruction: string; crease: FoldCrease; arrows: Array<{ from: Point2D; to: Point2D }>; checkpoint: string; toleranceMm: number }
export interface FoldInstructionSet { genomeId: string; aircraftName: string; learner: LearnerProfile; estimatedMinutes: number; materials: string[]; safetyNotes: string[]; steps: FoldStep[] }

function baseSteps(genome: AircraftGenome, learner: LearnerProfile): FoldStep[] {
  const narrow = genome.family === 'narrow-dart' || genome.family === 'dart-glider'
  const broad = genome.family === 'broad-glider' || genome.family === 'flying-wing' || genome.family === 'payload-carrier'
  const noseY = narrow ? 0.34 : broad ? 0.27 : 0.3
  const wingY = narrow ? 0.58 : broad ? 0.51 : 0.55
  const tolerance = learner === 'explorer' ? 3 : learner === 'investigator' ? 2 : 1.5
  return [
    { id: 'centerline', number: 1, title: 'Establish the centerline', instruction: instructionVerb(learner, 'Fold the paper in half the long way, press the crease, then open it.', 'Valley-fold the longitudinal centerline, sharpen the datum crease, and reopen the sheet.'), crease: { start: { x: 0.5, y: 0 }, end: { x: 0.5, y: 1 }, orientation: 'valley', movingSide: 'right', targetAngleDeg: 180 }, arrows: [{ from: { x: 0.84, y: 0.5 }, to: { x: 0.53, y: 0.5 } }], checkpoint: 'The sheet lies flat with one straight center crease.', toleranceMm: tolerance },
    { id: 'nose-corners', number: 2, title: 'Form the nose guide', instruction: instructionVerb(learner, 'Fold both top corners to the center crease.', 'Bring both leading corners symmetrically to the center datum without overlapping.'), crease: { start: { x: 0, y: noseY }, end: { x: 0.5, y: 0 }, orientation: 'valley', movingSide: 'top', targetAngleDeg: 180 }, arrows: [{ from: { x: 0.1, y: 0.06 }, to: { x: 0.48, y: noseY * 0.55 } }, { from: { x: 0.9, y: 0.06 }, to: { x: 0.52, y: noseY * 0.55 } }], checkpoint: 'The two folded edges meet evenly on the centerline.', toleranceMm: tolerance },
    { id: 'nose-lock', number: 3, title: narrow ? 'Sharpen the dart nose' : 'Lock the broad nose', instruction: narrow ? instructionVerb(learner, 'Fold the slanted edges to the center again.', 'Create the second symmetric nose taper by folding both exposed leading edges to the datum.') : instructionVerb(learner, 'Fold the pointed nose down, then tuck the corners under it.', 'Lower the nose flap to create a locking pocket and capture both shoulder folds beneath it.'), crease: { start: { x: 0.14, y: narrow ? 0.46 : 0.37 }, end: { x: 0.5, y: narrow ? 0.11 : 0.22 }, orientation: 'valley', movingSide: 'both', targetAngleDeg: 180 }, arrows: [{ from: { x: 0.18, y: 0.34 }, to: { x: 0.46, y: 0.27 } }, { from: { x: 0.82, y: 0.34 }, to: { x: 0.54, y: 0.27 } }], checkpoint: 'The nose is locked and the left and right layers match.', toleranceMm: tolerance },
    { id: 'body-fold', number: 4, title: 'Close the fuselage', instruction: instructionVerb(learner, 'Fold the airplane in half along the first crease.', 'Mountain-fold the complete stack along the longitudinal datum with the nose layers outside.'), crease: { start: { x: 0.5, y: 0 }, end: { x: 0.5, y: 1 }, orientation: 'mountain', movingSide: 'right', targetAngleDeg: 180 }, arrows: [{ from: { x: 0.88, y: 0.68 }, to: { x: 0.54, y: 0.68 } }], checkpoint: 'The nose, tail, and lower edges align on both sides.', toleranceMm: tolerance },
    { id: 'wings', number: 5, title: 'Set the wing chord', instruction: instructionVerb(learner, 'Fold each wing down using the guide line. Match the second wing to the first.', 'Valley-fold each wing at the calculated chord line and mirror the first wing crease onto the second side.'), crease: { start: { x: 0.18, y: wingY }, end: { x: 0.82, y: wingY }, orientation: 'valley', movingSide: 'both', targetAngleDeg: 180 }, arrows: [{ from: { x: 0.25, y: wingY - 0.16 }, to: { x: 0.25, y: wingY + 0.18 } }, { from: { x: 0.75, y: wingY - 0.16 }, to: { x: 0.75, y: wingY + 0.18 } }], checkpoint: 'Both wing trailing edges are level and equally wide.', toleranceMm: tolerance },
    { id: 'dihedral', number: 6, title: 'Open the flight angle', instruction: instructionVerb(learner, `Open the wings so their tips rise slightly. Aim for about ${round(genome.geometry.dihedralDeg, 0)}° total dihedral.`, `Open the wing panels to approximately ${round(genome.geometry.dihedralDeg, 0)}° dihedral and verify equal incidence on both sides.`), crease: { start: { x: 0.5, y: 0.15 }, end: { x: 0.5, y: 0.92 }, orientation: 'mountain', movingSide: 'both', targetAngleDeg: genome.geometry.dihedralDeg }, arrows: [{ from: { x: 0.2, y: 0.65 }, to: { x: 0.14, y: 0.54 } }, { from: { x: 0.8, y: 0.65 }, to: { x: 0.86, y: 0.54 } }], checkpoint: 'Viewed from the front, the wing tips rise by the same amount.', toleranceMm: tolerance },
    { id: 'trim', number: 7, title: 'Set neutral trim', instruction: instructionVerb(learner, 'Bend both back wing edges up only a tiny amount, then check that they match.', `Set symmetric trailing-edge tabs to approximately ${round(genome.geometry.controlTabDeg, 1)}° and keep both deflections equal.`), crease: { start: { x: 0.13, y: 0.86 }, end: { x: 0.87, y: 0.86 }, orientation: genome.geometry.controlTabDeg >= 0 ? 'valley' : 'mountain', movingSide: 'bottom', targetAngleDeg: Math.abs(genome.geometry.controlTabDeg) }, arrows: [{ from: { x: 0.24, y: 0.91 }, to: { x: 0.24, y: 0.84 } }, { from: { x: 0.76, y: 0.91 }, to: { x: 0.76, y: 0.84 } }], checkpoint: 'The aircraft is ready for a gentle first flight and trim test.', toleranceMm: tolerance },
  ]
}

export function buildInstructionSet(genome: AircraftGenome, learner: LearnerProfile): FoldInstructionSet {
  return { genomeId: genome.id, aircraftName: genome.name, learner, estimatedMinutes: Math.round(5 + genome.foldComplexity * 12), materials: [`One ${Math.round(genome.sheet.widthM * 1000)} × ${Math.round(genome.sheet.lengthM * 1000)} mm sheet`, genome.materialId.replaceAll('-', ' '), ...(genome.payloadMassG > 0 ? [`A removable ${genome.payloadMassG} g payload attachment`] : []), 'A ruler and clear launch area'], safetyNotes: ['Do not launch toward faces, animals, glass, traffic, or fragile equipment.', 'Use only removable classroom-safe additions when construction level 2 is selected.'], steps: baseSteps(genome, learner) }
}
